name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t alvarogomen93/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true alvarogomen93/react-test npm test

      - run: docker build -t alvarogomen93/multi-client ./client
      - run: docker build -t alvarogomen93/multi-nginx ./nginx
      - run: docker build -t alvarogomen93/multi-server ./server
      - run: docker build -t alvarogomen93/multi-worker ./worker

      - run: docker push alvarogomen93/multi-client
      - run: docker push alvarogomen93/multi-nginx
      - run: docker push alvarogomen93/multi-server
      - run: docker push alvarogomen93/multi-worker
